### ISSUE TITLE
[M2] Write the Reflection (~500 words)

### ISSUE THREAD

**Issue by stepanz25** [UBC-MDS/suicide_indicator_r#26]

**Comment by qurat-azim** [comment]
@stepanz25 @ZilongYi @tieandrews please add your comments/challenges with individual graphs in this issue and I can combine all of them in a final reflection document

**Comment by stepanz25** [comment]
@qurat-azim, I have included some of my thoughts for your reflection. Hopefully it will be helpful.

What is implemented from my side:

In the first tab titled "Country Wide Comparison," the dashboard displays a stacked bar plot for two countries' suicide rates between two years depicted as a period in time. The potential persona can select the two countries they would like to compare, the year range, and view the stacked bar plot that compares suicide rates by gender.

Some things that do not work well or can be improved in the plot are:
 - if the year range selected is too wide, the plot does not skip the x-axis label making the axis too looking too cluttered.

What the dashboard does well:

- the dashboard provides minimalistic and easy-to-use interface for the persona with minimal clutter.
- the reactive elements are updates the graph interactively when the user selects different year range and countries.
- the dashboard is providing the visual representations and statistics in plots as well as in maps which makes it easier to visualize the numbers by countries.
 
Some limitations:

- dashboard only allows comparisons between two countries.
- the data set used to construct the dashboard is limited.

**Comment by qurat-azim** [comment]
Thank you for this @stepanz25. I am also going to add how the line charts needed to be split into two as gdp and suicide numbers are on different scales

**Comment by tieandrews** [comment]
Map design reflection:

Upon reflection having two separate tabs for a map of country GDP and suicide rates is unneeded as we can include both pieces of info in the tool tip. This adds only a little data wrangling complexity but makes for a much simpler experience to inspect a countries GDP and suicide rate.

The map doesn't perfectly fit the desired use case of comparing two countries because it is not easy to "select" and leave highlighted two separate countries. This means users who want to compare to countries have to hocver over one then hover over the other and remember the values which is not ideal. Hopefully the first graph page fits that need and then the map serves as a geographical reference tool instead of a strictly comparative tool.

**Comment by qurat-azim** [comment]
There is missing data for some countries. Upon close inspection, we observe that the country comparison successfully switches to showing only one country's statistics without running into an error. This can be improved in future versions to show a message about the unavailability of data for that particular country for the desired time period.

**Comment by ZilongYi** [comment]
Grouped bar chart refelct:

In some cases, the suicides counts for countries are not in the same scales. Given the considerations of countries' population, GPD, etc, suicide phenomenon might be severer even with low suicide counts. By just comparing the counts, plot might give wrong impression to the user at the first place. 

Instead of just showing counts, it might be suitable, in the future improvement, to add a line layer to the plot to show suicides counts per 100k population, which could somehow to avoid unintended misconception of the plot.

**Comment by qurat-azim** [comment]
All done and PR created
